module.exports = {
	"env": {
		"browser": true,
		"commonjs": true,
		"es2020": true,
		"node": true,
		"mocha": true,
	},
	"extends": [
		"eslint:recommended",
	],
	"ignorePatterns": [
        "node_modules/**",
        "dist/**",
    ],
    "parserOptions": {
        "sourceType": "module",
    	"ecmaVersion": "latest",
    },
    "rules": {
        "no-unused-vars": ["error", {
            "vars": "local",
            "args": "none",
            "ignoreRestSiblings": true,
        }],
        "no-empty": ["error", { "allowEmptyCatch": true }],
        "eqeqeq": ["error"],
        "no-caller": ["error"],
        "no-constructor-return": ["error"],
        "no-eval": ["error"],
        "no-extend-native": ["error"],
        "no-floating-decimal": ["error"],
        "no-extra-label": ["error"],
        "no-lone-blocks": ["error"],
        "no-proto": ["error"],
        "no-new-object": ["error"],
        "array-bracket-spacing": ["warn"],
        "multiline-comment-style": ["error", "separate-lines"],
        "comma-spacing": ["warn"],
        "comma-style": ["error", "last"],
        "comma-dangle": ["warn", "always-multiline"],
        "eol-last": ["error"],
        "func-call-spacing": ["error"],
        "key-spacing": ["error"],
        "keyword-spacing": ["error"],
        "line-comment-position": ["error", "above"],
        "no-lonely-if": ["error"],
        "no-multiple-empty-lines": ["error", { "max": 1 }],
        "no-trailing-spaces": ["error", {
            "skipBlankLines": true,
            "ignoreComments": true,
        }],
        "no-whitespace-before-property": ["error"],
        "brace-style": ["error", "1tbs", {
            "allowSingleLine": true,
        }],
        "object-curly-spacing": ["error", "always"],
        "operator-linebreak": ["error", "after"],
        "prefer-exponentiation-operator": ["warn"],
        "prefer-object-spread": ["warn"],
        "quotes": ["error", "single", {
            "allowTemplateLiterals": true
        }],
        "quote-props": ["error", "as-needed"],
        "semi": ["error"],
        "semi-spacing": ["error"],
        "semi-style": ["error"],
        "spaced-comment": ["error", "always"],
        "space-in-parens": ["error", "never"],
        "space-before-function-paren": ["error", {
            "anonymous": "never",
            "named": "never",
            "asyncArrow": "always",
        }],
        "space-before-blocks": ["error", "always"],
        "generator-star-spacing": ["error", {
            "before": false,
            "after": true,
            "anonymous": {
                "before": false,
                "after": false,
            },
            "method": {
                "before": false,
                "after": false,
            },
        }],
        "no-useless-constructor": ["error"],
        "no-var": ["error"],
        "object-shorthand": ["error", "always"],
        "prefer-rest-params": ["error"],
        "prefer-spread": ["error"],
        "rest-spread-spacing": ["error"],
        "yield-star-spacing": ["error", "after"],
    },
};
